[package]
name = "advanced_constrained_secret_santa"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
serde = {version = "1.0", features = ["derive"]}
json5 = "1.3"
base64 = "0.22"
serde_json = "1.0"